version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Test
          command: |
            . ./bin/activate-hermit
            go test -v ./...
      - run:
          name: Lint
          command: |
            . ./bin/activate-hermit
            golangci-lint run
